### ISSUE TITLE
example for simple HTTP JSONRPC server?

### ISSUE THREAD

**Issue by s3rj1k** [sourcegraph/jsonrpc2#22]
Please provide an example for simple HTTP JSONRPC server

**Comment by keegancsmith** [comment]
There are two aspects to this. Some people upgrade the HTTP conn to a websocket and use jsonrpc2 like a normal persistent bidirectional protocol. Others just send a list of JSONRPC2 requests in the body, and the response is a list of JSONRPC2 responses. Which one are you thinking of?

For websockets I'd suggest using https://godoc.org/github.com/gorilla/websocket

**Comment by s3rj1k** [comment]
Hi @keegancsmith, thanks for quick reply, I was interested in plain HTTP(no WS) example with 2 different JSONRPC2 methods defined

**Comment by s3rj1k** [comment]
bump

**Comment by s3rj1k** [comment]
Strange for you o say that use case above is not JSONRPC.

HTTP is a transport protocol, JSONRPC is a message specification.

Ok, thanks for your input. closing this
