### ISSUE TITLE
Remove Debug logging for library

### ISSUE THREAD

**Issue by s3rj1k** [sourcegraph/jsonrpc2#24]
This appears to be forgotten debug log entry
https://github.com/sourcegraph/jsonrpc2/blob/master/jsonrpc2.go#L579

Can you please remove it from code or add an ability to disable it via some configuration variable.

**Comment by unknwon** [comment]
cc @sqs I know it's 3 years ago but `git blame`s you... 😄

**Comment by sqs** [comment]
Yes, I will merge a PR to fix it

**Comment by s3rj1k** [comment]
do you guys actually use this lib?

**Comment by unknwon** [comment]
I think yes we do: https://sourcegraph.com/search?q=repo:%5Egithub%5C.com/sourcegraph/+github.com/sourcegraph/jsonrpc2&patternType=literal

**Comment by sqs** [comment]
Feel free to send up a PR to change it to your preferred behavior.

**Comment by s3rj1k** [comment]
@sqs https://github.com/sourcegraph/jsonrpc2/pull/31

**Comment by s3rj1k** [comment]
closing this as fixed by PR
