### ISSUE TITLE
[BUG] OnRecv() func logging, wrong case check?

### ISSUE THREAD

**Issue by s3rj1k** [sourcegraph/jsonrpc2#33]
Shouldn't [this](https://github.com/sourcegraph/jsonrpc2/blob/master/conn_opt.go#L46) 
```
case req != nil && resp == nil:
```

be like this

```
case req != nil:
```

for logging all request queries?

**Comment by s3rj1k** [comment]
@unknwon any thoughts on this?

**Comment by unknwon** [comment]
TBH... I have no idea.

**Comment by s3rj1k** [comment]
@unknwon 
https://github.com/sourcegraph/jsonrpc2/pull/34/files
some minor log issues

**Comment by s3rj1k** [comment]
PR merged, thanks, closing this.
