### ISSUE TITLE
Consider adding version tag

### ISSUE THREAD

**Issue by samherrmann** [sourcegraph/jsonrpc2#46]
Would it be possible to tag the latest commit with `v0.1.0`? This would make the installation of this package with `go get` a little nicer while a [v0 version still does not commit to any stability](https://blog.golang.org/publishing-go-modules#TOC_4.). Also, I fear the lack of a version number may turn people away from using this library. With a version tag, perhaps the `This package is experimental until further notice.` statement in the README can be removed since a version below v1 implies that the API may change? Thoughts?

**Comment by keegancsmith** [comment]
Done :) Thanks!
