### ISSUE TITLE
Accept a `nil` handler

### ISSUE THREAD

**Issue by josebalius** [sourcegraph/jsonrpc2#53]
At day job we use this package for mostly client interactions with an RPC server. At the moment we are forced to implement a `noopHandler` since we don't care about any requests made to us. It could be a nicer API if a `nil` handler could be provided and the pkg to ignore requests in that case.

Is this something you'll accept a PR for? It's only a few lines to update to guard against nil handlers.

**Comment by keegancsmith** [comment]
Guarding against nil handlers sounds good to me.

**Comment by josebalius** [comment]
Opened a PR: https://github.com/sourcegraph/jsonrpc2/pull/54
